### ISSUE TITLE
could not open addons/mmaInstall.php

### ISSUE THREAD

**Issue by finyte** [henrylwilliams/minepeon-plugin-MobileMinerApp#2]
I'm kind of a noob and after i follow the instructions including entering an api key and device name. But it still fails to open the file. Any help? Thanks.

**Comment by henrylwilliams** [comment]
My fault, in the instructions I forgot to add the folder...

I will correct that... try this:
sudo /usr/bin/php /home/minepeon/addons/mma/mmaInstall.php <email> <app_key> <machine_name>

**Comment by finyte** [comment]
Hey now I'm getting a open_basedir restriction in effect. File (/var/spool/cron/minepeon) is not within the Allowed paths (/usr/share/pear/:opt/minepeon/... Etc) on line 10. 

Not sure what to do. Thanks

**Comment by henrylwilliams** [comment]
What version of MinePeon are you trying to install this on?

**Comment by finyte** [comment]
3.6.11-15

**Comment by henrylwilliams** [comment]
MinePeon has only just hit the pre-release of 2.4.0, so I'm fairly certain that's not the correct version number, I would say that could be a version of a miner, but I know CGMiner just hit 3.6.0 a couple of days ago and BFGMiner is still in the 3.3.x range.

Feel free to send me a screenshot me@tk1337.com, but either you using this for something that it's not to be used with or I have no idea where you are getting that version number from.

**Comment by finyte** [comment]
I apologize I'm currently using 0.2.3a I believe the newest img off source forge. I was just reading the number given while running.

**Comment by henrylwilliams** [comment]
That still doesn't make much sense, as the number would probably be that of BFGMiner or CGMiner, which aren't in that version range; Please send screen shots to the above address.

**Comment by finyte** [comment]
I sent an email. That's the best I can do for you sorry.

**Comment by henrylwilliams** [comment]
I got it, thanks... do the following:

cd /opt/minepeon/addons/mma/
git pull
sudo reboot

(wait for it to come back up, then...)
/usr/bin/php /opt/minepeon/addons/mma/mmaInstall.php

Let me know if this solves your issue, very strange though I just loaded a fresh MinePeon 0.2.3a image on a SD card and can't replicate the issue.

**Comment by finyte** [comment]
Once I enter cd /opt/minepeon/addons/mma I get "no such file or directory"

**Comment by henrylwilliams** [comment]
I'm sorry

cd /home/minepeon/addons/mma/
git pull
sudo reboot

(wait for it to come back up, then...)
/usr/bin/php /home/minepeon/addons/mma/mmaInstall.php

Also, don't put spaces in the machine name, it will see each space as being a separate argument.

**Comment by finyte** [comment]
I tried your method and also did a fresh install and I'm still getting the same error but on line 11 now "can not open cron file"

**Comment by henrylwilliams** [comment]
I finally got the issue to be replicated, I have corrected the install script, please make another git pull

cd /home/minepeon/addons/
git pull
/usr/bin/php /home/minepeon/addons/mma/mmaInstall.php [email] [appKey] [machine_Name]

**Comment by henrylwilliams** [comment]
I made another update today; I was attempting to go around having to put things in the http directory, but seems that isn't working out all too well in 0.2.3a or lower, so I updated the code. It should be good for you now

**Comment by finyte** [comment]
Hey I tried the new one today and once I entered it nothing happened. It went to the next line?  Now I'm not sure if that means it worked but I'm not seeing anything on my mobile miner app. Thanks

**Comment by henrylwilliams** [comment]
If you didn't see any errors, then yes, it worked. It will issue the update command every minute to the MobileMinerApp servers.

**Comment by finyte** [comment]
Hmm. Well it must of worked but unfortunately it's not showing up on my app. Thanks for your help I really appreciate it!
