### ISSUE TITLE
ssl problems

### ISSUE THREAD

**Issue by stephenhoos** [henrylwilliams/minepeon-plugin-MobileMinerApp#3]
I am trying to install your project and I am getting a git error about your ssl cert.

SSL certificate problem: certificate is not yet valid

**Comment by henrylwilliams** [comment]
That's not an issue with the plugin. That is relating to MinePeon's self
signed certificate. There is a guide on the MinePeon forums for this issue.

On Friday, November 8, 2013, stephenhoos wrote:

> I am trying to install your project and I am getting a git error about
> your ssl cert.
> 
> SSL certificate problem: certificate is not yet valid
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/labmixz/minepeon-plugin-MobileMinerApp/issues/3
> .

## 

Thank you for your time,

_Henry Williams_
Web Applications Developer
+1.813.528.6690

**Comment by henrylwilliams** [comment]
Also, while I know this is a very old issue. If you use the `date` command at the terminal in MinePeon, you would probably realize the date/time isn't being set (probably states it's 1970) therefore the system thinks the SSL from gitHub is invalid as it's set in the future of 2013/2014, which is a ways away from 1970. You need to run the ntp update command or manually set the date/time within the OS.
