### ISSUE TITLE
Request: Support the Pools API

### ISSUE THREAD

**Issue by nwoolls** [henrylwilliams/minepeon-plugin-MobileMinerApp#8]
I've had a few users contact me about this. Any chance you folks would mind supporting the Pools API call and SWITCH command? It's very simple and would allow users to change pools from MobileMiner.

http://mobileminerapp.com#api

It's also possible to submit the current pool name back up to MobileMiner for each device, which is not currently sent.

Thanks in advance for your support!

**Comment by henrylwilliams** [comment]
I haven't had much time to put towards this lately, but I'll try looking at it soon, sorry for not getting to this a bit sooner.

**Comment by nwoolls** [comment]
No problem at all. Let me know if you have any questions.
